services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: npmp
      POSTGRES_PASSWORD: npmp
      POSTGRES_DB: npmp
    volumes:
      -db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U npmp"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://npmp:npmp@db:5432/npmp
    command: ["/wait-for-it.sh", "db:5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  db_data: